# Sidebar navigation

- label: 'Apresentação'
  link: '/'
- label: Introdução
  items:
    - label: 'Getting started'
      link: '/getting-started'
- label: Frontend
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
- label: Backend
  items:
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: Contato
  items:
    - label: FAQ
      link: /faq
